[tool.commitizen]
name = "cz_conventional_commits"
version = "0.9.4"
tag_format = "$version"
version_files = ["Cargo.toml:version", "pyproject.toml:version"]
update_changelog_on_bump = true

bump_message = "v$new_version"
