[project]
name = "report_core_dev"
version = "0.10.0"
description = "report-core-root"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[tool.uv]
dev-dependencies = [
    "maturin>=1.9.0",
    "ruff>=0.11.13",
]

[tool.uv.workspace]
members = [
    "core_pyo3",
]
